.TH SCITE 1 "2001 February 26"
.SH NAME
scite \- a programmers text editor
.SH SYNOPSIS
.br
.B scite
[file ..]
.SH DESCRIPTION
.B Scite
is a graphical GTK+ based editor. It has support
for indenting, highlighting, and shortcuts in a myriad
of languages and can be extended by editing object-oriented
configuration files.
.PP
Support is included for Java, C, C++, C#, Shell, Apache.
.SH ON-LINE HELP
Type Alt-H or Click the Help Pulldown menu.
.SH AUTHOR
Most of
.B Scite
was made by Neil Hodgson, with a lot of help from others.
See Help
.br
.SH BUGS
Probably.
