static char * back_xpm[] = {
"30 30 30 1",
" 	c None",
".	c #000000",
"+	c #F6F6F6",
"@	c #E6EAE6",
"#	c #FFFFFF",
"$	c #DEEADE",
"%	c #EEF2EE",
"&	c #101810",
"*	c #B4C6AC",
"=	c #EEEEEE",
"-	c #203020",
";	c #315931",
">	c #52814A",
",	c #73996A",
"'	c #83A573",
")	c #7BA573",
"!	c #83AA73",
"~	c #83AA7B",
"{	c #83AE7B",
"]	c #62915A",
"^	c #526D4A",
"/	c #4A7D41",
"(	c #739D6A",
"_	c #739962",
":	c #4A7539",
"<	c #628D52",
"[	c #417139",
"}	c #6AA562",
"|	c #5A8952",
"1	c #315929",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                    ..        ",
"                  ..+.        ",
"                ..@#+.        ",
"              ..$#+++.        ",
"            .. #+%+++.        ",
"          .& #%%%%%%+.        ",
"        ..*#=++@%%%%+-        ",
"        ..;>,')!~{~{].        ",
"          ..^/(~'~{~].        ",
"            ..;/_!'{].        ",
"              ..:/_'<.        ",
"                ..[}|.        ",
"                  ..1.        ",
"                    ..        ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              "};

static char * blist_xpm[] = {
"30 30 19 1",
" 	c None",
".	c #000000",
"+	c #949D8B",
"@	c #94856A",
"#	c #736952",
"$	c #CDC2AC",
"%	c #D5CEBD",
"&	c #A4A5A4",
"*	c #7B715A",
"=	c #414031",
"-	c #080800",
";	c #C5B69C",
">	c #B4AA83",
",	c #94896A",
"'	c #BDB294",
")	c #C5BA9C",
"!	c #9C8D73",
"~	c #5A5541",
"{	c #4A4431",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"      ..................      ",
"      .                .      ",
"      .     ..+        .      ",
"      .    .@#.+       .      ",
"      ......$@..........      ",
"      .    .%@.+       .      ",
"      .    .$@...&     .      ",
"      .    .$@.*=-..+  .      ",
"      ......;@.>#.,#....      ",
"      .  .#.;@.>@.>@.@#.      ",
"      .  .@.;'@>>@>>>>@.      ",
"      .  .>.;))''>>>>>#.      ",
"      ....>.>))')>>>>>#.      ",
"      .  .@!')))')>>>>~.      ",
"      .   .@>))))'>>>@{.      ",
"      .   .#>'))')>>>@.       ",
"      ......@))))'>>@#.       ",
"           .#>>)))>>@~.       ",
"            .@'))'>>#.        ",
"             .>'))>>~.        ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              "};

static char * close_xpm[] = {
"30 30 2 1",
" 	c None",
".	c #000000",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"           .    ..            ",
"           ..  ....           ",
"            .. ...            ",
"            .....             ",
"             ...              ",
"             ....             ",
"            ......            ",
"            .. ....           ",
"           ..   ....          ",
"           .     ..           ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              "};

static char * editcopy_xpm[] = {
"30 30 54 1",
" 	c None",
".	c #000000",
"+	c #D1D1BC",
"@	c #919182",
"#	c #272727",
"$	c #AEAEA8",
"%	c #B7B7A5",
"&	c #D4D4BE",
"*	c #D8D8C2",
"=	c #EAEAE2",
"-	c #707070",
";	c #B3B3AC",
">	c #D7D7C1",
",	c #DBDBC4",
"'	c #ACAC9B",
")	c #DDDDD9",
"!	c #42423A",
"~	c #A5A595",
"{	c #DADAC3",
"]	c #DEDEC7",
"^	c #E2E2CA",
"/	c #616156",
"(	c #A5A594",
"_	c #D9D9C3",
":	c #DDDDC6",
"<	c #E1E1C9",
"[	c #E4E4CD",
"}	c #BBBBA7",
"|	c #DCDCC5",
"1	c #E0E0C9",
"2	c #E3E3CC",
"3	c #E7E7CF",
"4	c #929284",
"5	c #DFDFC8",
"6	c #E2E2CB",
"7	c #E6E6CF",
"8	c #EAEAD2",
"9	c #B4B4A1",
"0	c #E5E5CE",
"a	c #E9E9D1",
"b	c #EDEDD5",
"c	c #EBEBD3",
"d	c #A3A391",
"e	c #AEAE9C",
"f	c #E8E8D0",
"g	c #ECECD4",
"h	c #F0F0D7",
"i	c #EEEED5",
"j	c #F2F2D9",
"k	c #F1F1D8",
"l	c #F5F5DC",
"m	c #A7A796",
"n	c #9F9F8F",
"o	c #A6A696",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"          ..                  ",
"        ..+@.                 ",
"      .#$%&*.    ..           ",
"      .=-;>,'. ..+@.          ",
"      .)!~{]^.#$%&*.          ",
"      ./(_:<[.=-;>,'.         ",
"      .}*|123.)!~{]^.         ",
"      .4,5678./(_:<[9.        ",
"       .]^0ab.}*|123cd.       ",
"       .e[fgh.4,5678ij.       ",
"        .3cd...]^0abklm.      ",
"        .n..  .e[fgho..       ",
"         .     .3cd..         ",
"            .  .n..           ",
"         .....  .             ",
"         .....                ",
"            .                 ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              "};

static char * editcut_xpm[] = {
"30 30 2 1",
" 	c None",
".	c #000000",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                     .        ",
"                   ..         ",
"                  ..          ",
"                 ..           ",
"                ..            ",
"       ....    ..     ...     ",
"      .   ..  ..   ....       ",
"      .   ...........         ",
"       ....   ....            ",
"             ..               ",
"            ...               ",
"           .  .               ",
"          .   .               ",
"          .  .                ",
"          ...                 ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              "};

static char * editpaste_xpm[] = {
"30 30 105 2",
"  	c None",
". 	c #000000",
"+ 	c #CFCDBE",
"@ 	c #CFCCBD",
"# 	c #CFCBBC",
"$ 	c #D0CFBE",
"% 	c #CFCEBE",
"& 	c #CECABB",
"* 	c #D1CFBE",
"= 	c #7E7E74",
"- 	c #2F2F2B",
"; 	c #595855",
"> 	c #A09F9C",
", 	c #CCC9BB",
"' 	c #595956",
") 	c #DDDDDA",
"! 	c #ACABA5",
"~ 	c #7E7C72",
"{ 	c #3E3C38",
"] 	c #CDC9BB",
"^ 	c #CCC9BA",
"/ 	c #4D4D4B",
"( 	c #7E7C73",
"_ 	c #CDCABB",
": 	c #CBC9BA",
"< 	c #CAC8B9",
"[ 	c #73736E",
"} 	c #4D4C46",
"| 	c #A4A195",
"1 	c #CAC7B8",
"2 	c #CFCDBD",
"3 	c #CFCCBC",
"4 	c #CFCBBB",
"5 	c #CAC9B9",
"6 	c #CAC8B8",
"7 	c #C9C6B8",
"8 	c #D1D1BC",
"9 	c #919182",
"0 	c #CBC9B9",
"a 	c #272727",
"b 	c #AEAEA8",
"c 	c #B7B7A5",
"d 	c #D4D4BE",
"e 	c #D8D8C2",
"f 	c #EAEAE2",
"g 	c #707070",
"h 	c #B3B3AC",
"i 	c #D7D7C1",
"j 	c #DBDBC4",
"k 	c #ACAC9B",
"l 	c #DDDDD9",
"m 	c #42423A",
"n 	c #A5A595",
"o 	c #DADAC3",
"p 	c #DEDEC7",
"q 	c #E2E2CA",
"r 	c #C9C7B8",
"s 	c #C9C5B6",
"t 	c #616156",
"u 	c #A5A594",
"v 	c #D9D9C3",
"w 	c #DDDDC6",
"x 	c #E1E1C9",
"y 	c #E4E4CD",
"z 	c #B4B4A1",
"A 	c #C7C5B5",
"B 	c #C5C1B1",
"C 	c #C0BEAB",
"D 	c #BBBBA7",
"E 	c #DCDCC5",
"F 	c #E0E0C9",
"G 	c #E3E3CC",
"H 	c #E7E7CF",
"I 	c #EBEBD3",
"J 	c #A3A391",
"K 	c #C3C0AF",
"L 	c #C3BFAE",
"M 	c #C2BEAE",
"N 	c #C1BDAC",
"O 	c #BAB8A5",
"P 	c #929284",
"Q 	c #DFDFC8",
"R 	c #E2E2CB",
"S 	c #E6E6CF",
"T 	c #EAEAD2",
"U 	c #EEEED5",
"V 	c #F2F2D9",
"W 	c #C0BBAA",
"X 	c #BCB9A6",
"Y 	c #B8B4A1",
"Z 	c #B7B3A0",
"` 	c #E5E5CE",
" .	c #E9E9D1",
"..	c #EDEDD5",
"+.	c #F1F1D8",
"@.	c #F5F5DC",
"#.	c #A7A796",
"$.	c #B9B5A1",
"%.	c #B8B4A0",
"&.	c #AEAE9C",
"*.	c #E8E8D0",
"=.	c #ECECD4",
"-.	c #F0F0D7",
";.	c #A6A696",
">.	c #9F9F8F",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                        . . .                               ",
"                    . . + @ # .             .               ",
"                . . $ % @ # & .       . . . . .             ",
"            . . * $ = - ; > & , .     . . . . .             ",
"          . * * * ' ) ! ~ { ] ^ .           .               ",
"          . * * $ / ! ( { _ , : < .                         ",
"            . $ % [ } | _ , : < 1 .   . .                   ",
"            . % 2 3 4 & ] : 5 6 7 . . 8 9 .                 ",
"              . @ # & _ ^ 0 6 . a b c d e .                 ",
"              . # & _ , : < 1 . f g h i j k .               ",
"                . & , : 5 1 7 . l m n o p q .               ",
"                . ] ^ 5 6 r s . t u v w x y z .             ",
"                  . : 1 A B C . D e E F G H I J .           ",
"                  . K L M N O . P j Q R S T U V .           ",
"                    . W X Y Z . . p q `  ...+.@.#..         ",
"                    . $.%.. .   . &.y *.=.-.;.. .           ",
"                      . .         . H I J . .               ",
"                                  . >.. .                   ",
"                                    .                       ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            "};

static char * filenew_xpm[] = {
"30 30 89 1",
" 	c None",
".	c #000000",
"+	c #ADAD9C",
"@	c #959585",
"#	c #DCDCC5",
"$	c #DFDFC8",
"%	c #242424",
"&	c #A7A796",
"*	c #D7D7C1",
"=	c #D9D9C3",
"-	c #DCDCC4",
";	c #DDDDC7",
">	c #E1E1CA",
",	c #A6A694",
"'	c #D6D6BF",
")	c #D8D8C2",
"!	c #DBDBC4",
"~	c #DFDFC7",
"{	c #E3E3CB",
"]	c #B2B29F",
"^	c #7C7C7C",
"/	c #646464",
"(	c #D5D5BD",
"_	c #D5D5BF",
":	c #D7D7C0",
"<	c #DADAC3",
"[	c #DEDEC6",
"}	c #E1E1C9",
"|	c #E5E5CD",
"1	c #E9E9D1",
"2	c #343434",
"3	c #E7E7E7",
"4	c #373736",
"5	c #B8B8A6",
"6	c #D3D3BC",
"7	c #D9D9C2",
"8	c #DDDDC5",
"9	c #E0E0C8",
"0	c #E8E8D0",
"a	c #ECECD4",
"b	c #EEEED5",
"c	c #ECECEC",
"d	c #EDEDED",
"e	c #3D3D37",
"f	c #CECEB7",
"g	c #E6E6CE",
"h	c #EAEAD2",
"i	c #F1F1D8",
"j	c #A5A594",
"k	c #EEEEE5",
"l	c #3C3C3C",
"m	c #8F8F80",
"n	c #D0D0B9",
"o	c #E4E4CB",
"p	c #EAEAD1",
"q	c #ECECD3",
"r	c #EFEFD6",
"s	c #F2F2D9",
"t	c #F3F3DA",
"u	c #EEEEE6",
"v	c #505050",
"w	c #929282",
"x	c #D1D1B9",
"y	c #E7E7CF",
"z	c #EBEBD2",
"A	c #F4F4DB",
"B	c #F5F5DC",
"C	c #969686",
"D	c #D2D2BC",
"E	c #E0E0C9",
"F	c #E9E9D0",
"G	c #EDEDD4",
"H	c #F0F0D7",
"I	c #BEBEAB",
"J	c #797973",
"K	c #D8D8C1",
"L	c #DDDDC6",
"M	c #98988F",
"N	c #E4E4CC",
"O	c #818174",
"P	c #E2E2CA",
"Q	c #BEBEAE",
"R	c #4E4E4E",
"S	c #828274",
"T	c #EBEBD3",
"U	c #BBBBA8",
"V	c #CDCDB8",
"W	c #4D4D45",
"X	c #A6A696",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"               .              ",
"             ..+.             ",
"           ..@#$%             ",
"         ..&*=-;>.            ",
"       ..,'**)!~{].           ",
"      .^/'(_:<[}|12           ",
"      .3456*789|0ab.          ",
"      .cdef_!9g0hbij.         ",
"      .kklmn9opqrist.         ",
"      .uvwx-}yzbittAB.        ",
"      ..CD!E{FGHtAABBI.       ",
"      .JK7L>ypbitBBBBB).      ",
"      .M!#$NyzbitBBBBBO.      ",
"       .~9P|1qrsABBBB..       ",
"       .Q||0hGHtABB<.         ",
"        R01hGrstAsS.          ",
"        .TaGriss<.            ",
"         .rHis1j.             ",
"         .UstVW.              ",
"          .tX.                ",
"           ..                 ",
"                              ",
"                              ",
"                              ",
"                              "};

static char * fileopen_xpm[] = {
"30 30 5 1",
" 	c None",
".	c #000000",
"+	c #99907B",
"@	c #FFFEF7",
"#	c #FFFFFF",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                 ..           ",
"              ...++.          ",
"       ..  ...++++@@#...      ",
"      .++..++++@@@@..++.      ",
"      .+++++@@@@@..++++.      ",
"       .++@@@@@..++++++.      ",
"       .++@@@..++++++++.      ",
"        .+@@.++++++++++.      ",
"        .++@.++++++++++.      ",
"         .+@.++++++++++.      ",
"         .++.++++++++..       ",
"          .+.++++++..         ",
"          .+.+++++.           ",
"           ..+++..            ",
"           ..+..              ",
"            ..                ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              "};

static char * filesave_xpm[] = {
"30 30 64 1",
" 	c None",
".	c #000000",
"+	c #779FA8",
"@	c #495A5E",
"#	c #BFD1D5",
"$	c #A8C1C5",
"%	c #E4ECED",
"&	c #FFFFFF",
"*	c #EEF3F4",
"=	c #E0E9EB",
"-	c #87AAB2",
";	c #AEC4C9",
">	c #F5F8F9",
",	c #8BADB5",
"'	c #3E4D50",
")	c #94B2B9",
"!	c #CFDCDF",
"~	c #E4ECEE",
"{	c #788A8D",
"]	c #EBF1F2",
"^	c #E8EFF0",
"/	c #F2F6F7",
"(	c #607A7F",
"_	c #F0F4F5",
":	c #536E75",
"<	c #A0BCC1",
"[	c #465E63",
"}	c #4B575A",
"|	c #557278",
"1	c #A4ABAD",
"2	c #EAEAEA",
"3	c #E4E4E4",
"4	c #606364",
"5	c #C6CACC",
"6	c #F3F3F3",
"7	c #F1F1F1",
"8	c #E7E7E7",
"9	c #E1E1E1",
"0	c #A9B2B4",
"a	c #486166",
"b	c #34464A",
"c	c #729096",
"d	c #BCC2C3",
"e	c #F6F6F6",
"f	c #57696D",
"g	c #CFD8DA",
"h	c #DEDEDE",
"i	c #D8D8D8",
"j	c #8C9394",
"k	c #F2F2F2",
"l	c #3A474A",
"m	c #7EA4AC",
"n	c #D5DADA",
"o	c #E0E0E0",
"p	c #B4B4B4",
"q	c #657376",
"r	c #D0D5D6",
"s	c #E9E9E9",
"t	c #A7B0B2",
"u	c #D2D4D5",
"v	c #899293",
"w	c #484848",
"x	c #DDDDDD",
"y	c #8F9A9B",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                 ..           ",
"               ..+@.          ",
"             ..#$%+.          ",
"           ..#$#&*+@.         ",
"         ..#$#&&&&=+.         ",
"       ..-;#&&&&&&>,'.        ",
"      .);!&&&&&&&&&~+.        ",
"      .{)]&&&&&&&&&^+@.       ",
"       .$=&&&&&&&/=+++.       ",
"       .(-]&&&&_=++::+@.      ",
"        .<=&&_=++[}|+:+.      ",
"        .(-^=++[1234+:+@.     ",
"         .)++:567890a+[b.     ",
"         .c-+defg3hij+'..     ",
"          .)+:klmnopq..       ",
"          .|++rstuvw.         ",
"           .a+:xy..           ",
"            .....             ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              "};

static char * next_xpm[] = {
"30 30 31 1",
" 	c None",
".	c #000000",
"+	c #E6EADE",
"@	c #FFFFFF",
"#	c #F6F6EE",
"$	c #F6F6F6",
"%	c #EEF2EE",
"&	c #E6EEE6",
"*	c #181818",
"=	c #292829",
"-	c #B4C6AC",
";	c #9CBA94",
">	c #8BAE83",
",	c #83AA7B",
"'	c #7BA573",
")	c #83A57B",
"!	c #73996A",
"~	c #5A814A",
"{	c #395931",
"]	c #9CBA8B",
"^	c #83AE7B",
"/	c #739D6A",
"(	c #527D4A",
"_	c #415941",
":	c #83A573",
"<	c #4A7141",
"[	c #94B283",
"}	c #395D31",
"|	c #5A8552",
"1	c #315929",
"2	c #396531",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"         ..                   ",
"         .+..                 ",
"         .@#$..               ",
"         .@$%#$..             ",
"         .@$$%%$ ..           ",
"         .@%%%%%&#$*.         ",
"         =@%%%%$$$$%-..       ",
"         .;>,>,,')!~{..       ",
"         .],^,),/(_..         ",
"         .]^:,!(<..           ",
"         .[:!(}..             ",
"         .,|1..               ",
"         .2..                 ",
"         ..                   ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              "};

static char * prev_xpm[] = {
"30 30 30 1",
" 	c None",
".	c #000000",
"+	c #F6F6F6",
"@	c #E6EAE6",
"#	c #FFFFFF",
"$	c #DEEADE",
"%	c #EEF2EE",
"&	c #101810",
"*	c #B4C6AC",
"=	c #EEEEEE",
"-	c #203020",
";	c #315931",
">	c #52814A",
",	c #73996A",
"'	c #83A573",
")	c #7BA573",
"!	c #83AA73",
"~	c #83AA7B",
"{	c #83AE7B",
"]	c #62915A",
"^	c #526D4A",
"/	c #4A7D41",
"(	c #739D6A",
"_	c #739962",
":	c #4A7539",
"<	c #628D52",
"[	c #417139",
"}	c #6AA562",
"|	c #5A8952",
"1	c #315929",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                    ..        ",
"                  ..+.        ",
"                ..@#+.        ",
"              ..$#+++.        ",
"            .. #+%+++.        ",
"          .& #%%%%%%+.        ",
"        ..*#=++@%%%%+-        ",
"        ..;>,')!~{~{].        ",
"          ..^/(~'~{~].        ",
"            ..;/_!'{].        ",
"              ..:/_'<.        ",
"                ..[}|.        ",
"                  ..1.        ",
"                    ..        ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              "};

static char * redo_xpm[] = {
"30 30 8 1",
" 	c None",
".	c #000000",
"+	c #4C603C",
"@	c #566B43",
"#	c #445636",
"$	c #526741",
"%	c #5A7046",
"&	c #37452B",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                 .            ",
"                 ..           ",
"              ...+@.          ",
"            ..#+$$%$.         ",
"           .##...$@.          ",
"           .&.   ..           ",
"          .&.    .            ",
"          ..                  ",
"          ..                  ",
"           .                  ",
"            .                 ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              "};

static char * replace_xpm[] = {
"30 30 126 2",
"  	c None",
". 	c #000000",
"+ 	c #D8BE6A",
"@ 	c #8E7D45",
"# 	c #ADAD9C",
"$ 	c #959585",
"% 	c #DCDCC5",
"& 	c #DFDFC8",
"* 	c #A7A796",
"= 	c #D7D7C1",
"- 	c #D9D9C3",
"; 	c #DCDCC4",
"> 	c #A6A694",
", 	c #D6D6BF",
"' 	c #D8D8C2",
") 	c #7C7C7C",
"! 	c #646464",
"~ 	c #D5D5BD",
"{ 	c #D5D5BF",
"] 	c #D7D7C0",
"^ 	c #C6B273",
"/ 	c #756020",
"( 	c #E9E9D1",
"_ 	c #343434",
": 	c #E7E7E7",
"< 	c #373736",
"[ 	c #B8B8A6",
"} 	c #D3D3BC",
"| 	c #D9D9C2",
"1 	c #060605",
"2 	c #E5E5CD",
"3 	c #E8E8D0",
"4 	c #ECECD4",
"5 	c #EEEED5",
"6 	c #ECECEC",
"7 	c #EDEDED",
"8 	c #3D3D37",
"9 	c #CECEB7",
"0 	c #DBDBC4",
"a 	c #E0E0C8",
"b 	c #E6E6CE",
"c 	c #EAEAD2",
"d 	c #F1F1D8",
"e 	c #A5A594",
"f 	c #EEEEE5",
"g 	c #3C3C3C",
"h 	c #8F8F80",
"i 	c #D0D0B9",
"j 	c #B4B4A0",
"k 	c #46463E",
"l 	c #090908",
"m 	c #4A4A42",
"n 	c #C1C1AD",
"o 	c #F2F2D9",
"p 	c #F3F3DA",
"q 	c #EEEEE6",
"r 	c #505050",
"s 	c #929282",
"t 	c #D1D1B9",
"u 	c #B0B09D",
"v 	c #33332D",
"w 	c #9D9D8D",
"x 	c #CFCFB9",
"y 	c #C4C4AF",
"z 	c #8D8D7F",
"A 	c #34342F",
"B 	c #C3C3AF",
"C 	c #F4F4DB",
"D 	c #F5F5DC",
"E 	c #969686",
"F 	c #D2D2BC",
"G 	c #45453E",
"H 	c #9C9C8C",
"I 	c #E2E2D0",
"J 	c #EDEDE5",
"K 	c #C0C0AC",
"L 	c #B2B29F",
"M 	c #828274",
"N 	c #4B4B43",
"O 	c #BEBEAB",
"P 	c #797973",
"Q 	c #D8D8C1",
"R 	c #DDDDC6",
"S 	c #080807",
"T 	c #FBFBFA",
"U 	c #C3C3AE",
"V 	c #B5B5A2",
"W 	c #A6A695",
"X 	c #959586",
"Y 	c #98988F",
"Z 	c #080808",
"` 	c #CACAB5",
" .	c #DDDDD0",
"..	c #B7B7A4",
"+.	c #AAAA98",
"@.	c #9B9B8B",
"#.	c #8C8C7D",
"$.	c #818174",
"%.	c #DFDFC7",
"&.	c #E2E2CA",
"*.	c #46463F",
"=.	c #929283",
"-.	c #BABAA7",
";.	c #ADAD9B",
">.	c #9F9F8E",
",.	c #909081",
"'.	c #727266",
").	c #4B4B44",
"!.	c #BEBEAE",
"~.	c #33332E",
"{.	c #878779",
"].	c #A0A090",
"^.	c #737367",
"/.	c #DADAC3",
"(.	c #4E4E4E",
"_.	c #BEBEAA",
":.	c #404040",
"<.	c #6F6F6F",
"[.	c #EBEBD3",
"}.	c #EDEDD4",
"|.	c #EFEFD6",
"1.	c #F0F0D7",
"2.	c #BBBBA8",
"3.	c #CDCDB8",
"4.	c #4D4D45",
"5.	c #A6A696",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                        . .                 ",
"                                      . + @ .               ",
"                              .     . + @ .                 ",
"                          . . # . . + @ .                   ",
"                      . . $ % & . + @ .                     ",
"                  . . * = - ; . + @ .                       ",
"              . . > , = = ' . + @ . .                       ",
"            . ) ! , ~ { ] ^ / . . ( _                       ",
"            . : < [ } = | 1 . 2 3 4 5 .                     ",
"            . 6 7 8 9 { 0 a b 3 c 5 d e .                   ",
"            . f f g h i j k l l m n o p .                   ",
"            . q r s t u v w x y z A B C D .                 ",
"            . . E F 0 G H I J K L M N D D O .               ",
"            . P Q | R S { T U V W X l D D D ' .             ",
"            . Y 0 % & Z `  ...+.@.#.l D D D $..             ",
"              . %.a &.*.=.-.;.>.,.'.).D D . .               ",
"              . !.2 2 -.~.{.].=.^.. . /..                   ",
"                (.3 ( c _.m l l :.<.. .                     ",
"                . [.4 }.|.d o o /.. . . .                   ",
"                  . |.1.d o ( e .     . . .                 ",
"                  . 2.o p 3.4..         . . .               ",
"                    . p 5..               . .               ",
"                      . .                                   ",
"                                                            ",
"                                                            ",
"                                                            "};

static char * search_xpm[] = {
"30 30 128 2",
"  	c None",
". 	c #000000",
"+ 	c #ADAD9C",
"@ 	c #959585",
"# 	c #DCDCC5",
"$ 	c #DFDFC8",
"% 	c #242424",
"& 	c #A7A796",
"* 	c #D7D7C1",
"= 	c #D9D9C3",
"- 	c #DCDCC4",
"; 	c #DDDDC7",
"> 	c #E1E1CA",
", 	c #A6A694",
"' 	c #D6D6BF",
") 	c #D8D8C2",
"! 	c #DBDBC4",
"~ 	c #DFDFC7",
"{ 	c #E3E3CB",
"] 	c #B2B29F",
"^ 	c #7C7C7C",
"/ 	c #646464",
"( 	c #D5D5BD",
"_ 	c #D5D5BF",
": 	c #D7D7C0",
"< 	c #DADAC3",
"[ 	c #DEDEC6",
"} 	c #E1E1C9",
"| 	c #E5E5CD",
"1 	c #E9E9D1",
"2 	c #343434",
"3 	c #E7E7E7",
"4 	c #373736",
"5 	c #B8B8A6",
"6 	c #D3D3BC",
"7 	c #D9D9C2",
"8 	c #DDDDC5",
"9 	c #E0E0C8",
"0 	c #E8E8D0",
"a 	c #ECECD4",
"b 	c #EEEED5",
"c 	c #ECECEC",
"d 	c #EDEDED",
"e 	c #3D3D37",
"f 	c #CECEB7",
"g 	c #E6E6CE",
"h 	c #EAEAD2",
"i 	c #F1F1D8",
"j 	c #A5A594",
"k 	c #EEEEE5",
"l 	c #3C3C3C",
"m 	c #8F8F80",
"n 	c #D0D0B9",
"o 	c #B4B4A0",
"p 	c #46463E",
"q 	c #090908",
"r 	c #4A4A42",
"s 	c #C1C1AD",
"t 	c #F2F2D9",
"u 	c #F3F3DA",
"v 	c #EEEEE6",
"w 	c #505050",
"x 	c #929282",
"y 	c #D1D1B9",
"z 	c #B0B09D",
"A 	c #33332D",
"B 	c #9D9D8D",
"C 	c #CFCFB9",
"D 	c #C4C4AF",
"E 	c #8D8D7F",
"F 	c #34342F",
"G 	c #C3C3AF",
"H 	c #F4F4DB",
"I 	c #F5F5DC",
"J 	c #969686",
"K 	c #D2D2BC",
"L 	c #45453E",
"M 	c #9C9C8C",
"N 	c #E2E2D0",
"O 	c #EDEDE5",
"P 	c #C0C0AC",
"Q 	c #828274",
"R 	c #4B4B43",
"S 	c #BEBEAB",
"T 	c #797973",
"U 	c #D8D8C1",
"V 	c #DDDDC6",
"W 	c #080807",
"X 	c #FBFBFA",
"Y 	c #C3C3AE",
"Z 	c #B5B5A2",
"` 	c #A6A695",
" .	c #959586",
"..	c #98988F",
"+.	c #080808",
"@.	c #CACAB5",
"#.	c #DDDDD0",
"$.	c #B7B7A4",
"%.	c #AAAA98",
"&.	c #9B9B8B",
"*.	c #8C8C7D",
"=.	c #818174",
"-.	c #E2E2CA",
";.	c #46463F",
">.	c #929283",
",.	c #BABAA7",
"'.	c #ADAD9B",
").	c #9F9F8E",
"!.	c #909081",
"~.	c #727266",
"{.	c #4B4B44",
"].	c #BEBEAE",
"^.	c #33332E",
"/.	c #878779",
"(.	c #A0A090",
"_.	c #737367",
":.	c #4E4E4E",
"<.	c #BEBEAA",
"[.	c #404040",
"}.	c #6F6F6F",
"|.	c #EBEBD3",
"1.	c #EDEDD4",
"2.	c #EFEFD6",
"3.	c #F0F0D7",
"4.	c #BBBBA8",
"5.	c #CDCDB8",
"6.	c #4D4D45",
"7.	c #A6A696",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                              .                             ",
"                          . . + .                           ",
"                      . . @ # $ %                           ",
"                  . . & * = - ; > .                         ",
"              . . , ' * * ) ! ~ { ] .                       ",
"            . ^ / ' ( _ : < [ } | 1 2                       ",
"            . 3 4 5 6 * 7 8 9 | 0 a b .                     ",
"            . c d e f _ ! 9 g 0 h b i j .                   ",
"            . k k l m n o p q q r s t u .                   ",
"            . v w x y z A B C D E F G H I .                 ",
"            . . J K ! L M N O P ] Q R I I S .               ",
"            . T U 7 V W _ X Y Z `  .q I I I ) .             ",
"            . ..! # $ +.@.#.$.%.&.*.q I I I =..             ",
"              . ~ 9 -.;.>.,.'.).!.~.{.I I . .               ",
"              . ].| | ,.^./.(.>._.. . < .                   ",
"                :.0 1 h <.r q q [.}.. .                     ",
"                . |.a 1.2.i t t < . . . .                   ",
"                  . 2.3.i t 1 j .     . . .                 ",
"                  . 4.t u 5.6..         . . .               ",
"                    . u 7..               . .               ",
"                      . .                                   ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            "};

static char * undo_xpm[] = {
"30 30 8 1",
" 	c None",
".	c #000000",
"+	c #8F431E",
"@	c #803C1B",
"#	c #8A411D",
"$	c #954620",
"%	c #733618",
"&	c #5C2B13",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"             .                ",
"            ..                ",
"           .+@...             ",
"          .#$##@%..           ",
"           .+#...%%.          ",
"            ..   .&.          ",
"             .    .&.         ",
"                   ..         ",
"                   ..         ",
"                   .          ",
"                  .           ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              ",
"                              "};

static char * findnext_xpm[] = {
"30 30 128 2",
"  	c None",
". 	c #000000",
"+ 	c #797973",
"@ 	c #ADAD9C",
"# 	c #DCDCC5",
"$ 	c #959585",
"% 	c #DFDFC8",
"& 	c #242424",
"* 	c #A7A796",
"= 	c #D7D7C1",
"- 	c #D9D9C3",
"; 	c #DCDCC4",
"> 	c #DDDDC7",
", 	c #E1E1CA",
"' 	c #A6A694",
") 	c #D6D6BF",
"! 	c #D8D8C2",
"~ 	c #DBDBC4",
"{ 	c #DFDFC7",
"] 	c #E3E3CB",
"^ 	c #B2B29F",
"/ 	c #7C7C7C",
"( 	c #646464",
"_ 	c #D5D5BD",
": 	c #D5D5BF",
"< 	c #D7D7C0",
"[ 	c #DADAC3",
"} 	c #DEDEC6",
"| 	c #E1E1C9",
"1 	c #E5E5CD",
"2 	c #E9E9D1",
"3 	c #343434",
"4 	c #E7E7E7",
"5 	c #373736",
"6 	c #B8B8A6",
"7 	c #D3D3BC",
"8 	c #D9D9C2",
"9 	c #DDDDC5",
"0 	c #E0E0C8",
"a 	c #E8E8D0",
"b 	c #ECECD4",
"c 	c #EEEED5",
"d 	c #ECECEC",
"e 	c #EDEDED",
"f 	c #3D3D37",
"g 	c #CECEB7",
"h 	c #E6E6CE",
"i 	c #EAEAD2",
"j 	c #F1F1D8",
"k 	c #A5A594",
"l 	c #EEEEE5",
"m 	c #3C3C3C",
"n 	c #8F8F80",
"o 	c #D0D0B9",
"p 	c #B4B4A0",
"q 	c #46463E",
"r 	c #090908",
"s 	c #4A4A42",
"t 	c #C1C1AD",
"u 	c #F2F2D9",
"v 	c #F3F3DA",
"w 	c #EEEEE6",
"x 	c #505050",
"y 	c #929282",
"z 	c #D1D1B9",
"A 	c #B0B09D",
"B 	c #33332D",
"C 	c #9D9D8D",
"D 	c #CFCFB9",
"E 	c #C4C4AF",
"F 	c #8D8D7F",
"G 	c #34342F",
"H 	c #C3C3AF",
"I 	c #F4F4DB",
"J 	c #F5F5DC",
"K 	c #969686",
"L 	c #D2D2BC",
"M 	c #45453E",
"N 	c #9C9C8C",
"O 	c #E2E2D0",
"P 	c #EDEDE5",
"Q 	c #C0C0AC",
"R 	c #828274",
"S 	c #4B4B43",
"T 	c #BEBEAB",
"U 	c #D8D8C1",
"V 	c #DDDDC6",
"W 	c #080807",
"X 	c #FBFBFA",
"Y 	c #C3C3AE",
"Z 	c #B5B5A2",
"` 	c #A6A695",
" .	c #959586",
"..	c #98988F",
"+.	c #080808",
"@.	c #CACAB5",
"#.	c #DDDDD0",
"$.	c #B7B7A4",
"%.	c #AAAA98",
"&.	c #9B9B8B",
"*.	c #8C8C7D",
"=.	c #818174",
"-.	c #E2E2CA",
";.	c #46463F",
">.	c #929283",
",.	c #BABAA7",
"'.	c #ADAD9B",
").	c #9F9F8E",
"!.	c #909081",
"~.	c #727266",
"{.	c #4B4B44",
"].	c #BEBEAE",
"^.	c #33332E",
"/.	c #878779",
"(.	c #A0A090",
"_.	c #737367",
":.	c #4E4E4E",
"<.	c #BEBEAA",
"[.	c #404040",
"}.	c #6F6F6F",
"|.	c #EBEBD3",
"1.	c #EDEDD4",
"2.	c #EFEFD6",
"3.	c #F0F0D7",
"4.	c #BBBBA8",
"5.	c #CDCDB8",
"6.	c #4D4D45",
"7.	c #A6A696",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                              .     + . +   + . +   + . +   ",
"                          . . @ .   . # .   . # .   . # .   ",
"                      . . $ # % &   + . +   + . +   + . +   ",
"                  . . * = - ; > , .                         ",
"              . . ' ) = = ! ~ { ] ^ .                       ",
"            . / ( ) _ : < [ } | 1 2 3                       ",
"            . 4 5 6 7 = 8 9 0 1 a b c .                     ",
"            . d e f g : ~ 0 h a i c j k .                   ",
"            . l l m n o p q r r s t u v .                   ",
"            . w x y z A B C D E F G H I J .                 ",
"            . . K L ~ M N O P Q ^ R S J J T .               ",
"            . + U 8 V W : X Y Z `  .r J J J ! .             ",
"            . ..~ # % +.@.#.$.%.&.*.r J J J =..             ",
"              . { 0 -.;.>.,.'.).!.~.{.J J . .               ",
"              . ].1 1 ,.^./.(.>._.. . [ .                   ",
"                :.a 2 i <.s r r [.}.. .                     ",
"                . |.b 1.2.j u u [ . . . .                   ",
"                  . 2.3.j u 2 k .     . . .                 ",
"                  . 4.u v 5.6..         . . .               ",
"                    . v 7..               . .               ",
"                      . .                                   ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            "};

static char * findinfiles_xpm[] = {
"30 30 128 2",
"  	c None",
". 	c #000000",
"+ 	c #ADAD9C",
"@ 	c #959585",
"# 	c #DCDCC5",
"$ 	c #DFDFC8",
"% 	c #242424",
"& 	c #818174",
"* 	c #A7A796",
"= 	c #D7D7C1",
"- 	c #D9D9C3",
"; 	c #DCDCC4",
"> 	c #DDDDC7",
", 	c #E1E1CA",
"' 	c #A6A694",
") 	c #D6D6BF",
"! 	c #D8D8C2",
"~ 	c #DBDBC4",
"{ 	c #DFDFC7",
"] 	c #E3E3CB",
"^ 	c #B2B29F",
"/ 	c #7C7C7C",
"( 	c #646464",
"_ 	c #D5D5BD",
": 	c #D5D5BF",
"< 	c #D7D7C0",
"[ 	c #DADAC3",
"} 	c #DEDEC6",
"| 	c #E1E1C9",
"1 	c #E5E5CD",
"2 	c #E9E9D1",
"3 	c #343434",
"4 	c #E7E7E7",
"5 	c #373736",
"6 	c #B8B8A6",
"7 	c #D3D3BC",
"8 	c #D9D9C2",
"9 	c #DDDDC5",
"0 	c #E0E0C8",
"a 	c #E8E8D0",
"b 	c #ECECD4",
"c 	c #EEEED5",
"d 	c #ECECEC",
"e 	c #EDEDED",
"f 	c #3D3D37",
"g 	c #CECEB7",
"h 	c #E6E6CE",
"i 	c #EAEAD2",
"j 	c #F1F1D8",
"k 	c #A5A594",
"l 	c #EEEEE5",
"m 	c #3C3C3C",
"n 	c #8F8F80",
"o 	c #D0D0B9",
"p 	c #B4B4A0",
"q 	c #46463E",
"r 	c #090908",
"s 	c #4A4A42",
"t 	c #C1C1AD",
"u 	c #F2F2D9",
"v 	c #F3F3DA",
"w 	c #EEEEE6",
"x 	c #505050",
"y 	c #929282",
"z 	c #D1D1B9",
"A 	c #B0B09D",
"B 	c #33332D",
"C 	c #9D9D8D",
"D 	c #CFCFB9",
"E 	c #C4C4AF",
"F 	c #8D8D7F",
"G 	c #34342F",
"H 	c #C3C3AF",
"I 	c #F4F4DB",
"J 	c #F5F5DC",
"K 	c #969686",
"L 	c #D2D2BC",
"M 	c #45453E",
"N 	c #9C9C8C",
"O 	c #E2E2D0",
"P 	c #EDEDE5",
"Q 	c #C0C0AC",
"R 	c #828274",
"S 	c #4B4B43",
"T 	c #BEBEAB",
"U 	c #797973",
"V 	c #D8D8C1",
"W 	c #DDDDC6",
"X 	c #080807",
"Y 	c #FBFBFA",
"Z 	c #C3C3AE",
"` 	c #B5B5A2",
" .	c #A6A695",
"..	c #959586",
"+.	c #98988F",
"@.	c #080808",
"#.	c #CACAB5",
"$.	c #DDDDD0",
"%.	c #B7B7A4",
"&.	c #AAAA98",
"*.	c #9B9B8B",
"=.	c #8C8C7D",
"-.	c #E2E2CA",
";.	c #46463F",
">.	c #929283",
",.	c #BABAA7",
"'.	c #ADAD9B",
").	c #9F9F8E",
"!.	c #909081",
"~.	c #727266",
"{.	c #4B4B44",
"].	c #BEBEAE",
"^.	c #33332E",
"/.	c #878779",
"(.	c #A0A090",
"_.	c #737367",
":.	c #4E4E4E",
"<.	c #BEBEAA",
"[.	c #404040",
"}.	c #6F6F6F",
"|.	c #EBEBD3",
"1.	c #EDEDD4",
"2.	c #EFEFD6",
"3.	c #F0F0D7",
"4.	c #BBBBA8",
"5.	c #CDCDB8",
"6.	c #4D4D45",
"7.	c #A6A696",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                              .       .                     ",
"                          . . + . . . + .                   ",
"                      . . @ # $ % & # # .                   ",
"                  . . * = - ; > , . # # # .                 ",
"              . . ' ) = = ! ~ { ] ^ . # # + .               ",
"            . / ( ) _ : < [ } | 1 2 3 # # # .               ",
"            . 4 5 6 7 = 8 9 0 1 a b c . # # # .             ",
"            . d e f g : ~ 0 h a i c j k . # # + .           ",
"            . l l m n o p q r r s t u v . # # # .           ",
"            . w x y z A B C D E F G H I J . # # # .         ",
"            . . K L ~ M N O P Q ^ R S J J T . # # + .       ",
"            . U V 8 W X : Y Z `  ...r J J J ! . # # + .     ",
"            . +.~ # $ @.#.$.%.&.*.=.r J J J & . # # & .     ",
"              . { 0 -.;.>.,.'.).!.~.{.J J . . # # . .       ",
"              . ].1 1 ,.^./.(.>._.. . [ . # # + .           ",
"                :.a 2 i <.s r r [.}.. . # # . .             ",
"                . |.b 1.2.j u u [ . . . . .                 ",
"                  . 2.3.j u 2 k . # # . . .                 ",
"                  . 4.u v 5.6.. # # . . . . .               ",
"                    . v 7.. . # & .       . .               ",
"                      . .     . .                           ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            "};
